[repo]
minVersion = "v0.1.0"

title = "Luma"
summary = "Stapler-репозиторий с приложениями"
description = """
Luma — Stapler-репозиторий, содержащий сборочные скрипты
для установки приложений через Stapler."""
homepage = "https://github.com/Cheviiot/Luma"
icon = "https://raw.githubusercontent.com/Cheviiot/Luma/main/.github/assets/icon.svg"

url = "https://github.com/Cheviiot/Luma.git"
ref = "main"
mirrors = [
    "https://altlinux.space/Cheviiot/Luma.git",
]

report_url = "https://github.com/Cheviiot/Luma/issues/new?title={{ .BasePackageName }}"
