[repo]
minVersion = "v0.1.1"

title = "Luma"
summary = "Stapler-репозиторий для Linux-приложений"
description = """
Luma — Stapler-репозиторий, содержащий сборочные скрипты
для установки приложений через Stapler."""
homepage = "https://github.com/Cheviiot/luma"
icon = "https://raw.githubusercontent.com/Cheviiot/luma/main/.github/assets/icon.svg"

url = "https://github.com/Cheviiot/luma.git"
ref = "main"

report_url = "https://github.com/Cheviiot/luma/issues/new?title={{ .BasePackageName }}"
